version: '3.8'

services:
  webapp1:
    build:
      context: .
      dockerfile: ./apps/webapp1/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:4000
      - NEXT_PUBLIC_PYTHON_API_URL=http://python-api:5000

  webapp2:
    build:
      context: .
      dockerfile: ./apps/webapp2/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:4000
      - NEXT_PUBLIC_PYTHON_API_URL=http://python-api:5000

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN=http://webapp1:3000,http://webapp2:3001

  queue-worker:
    build:
      context: .
      dockerfile: ./apps/queue-worker/Dockerfile
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379

  python-api:
    build:
      context: ./apps/python-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DEBUG=false