import './globals.css';
import { AuthProvider } from '../components/auth-provider';

export const metadata = {
  title: 'Webapp 1',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}