name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: |
            apps/**
            packages/**

      - name: Install dependencies
        run: |
          npm ci
          pip install -r apps/python-api/requirements.txt

      - name: Build & Test affected
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          npx turbo run build test --filter=[origin/main] --parallel

      - name: Build & Test all
        if: steps.changed-files.outputs.any_changed != 'true'
        run: |
          npx turbo run build test --parallel